### ISSUE TITLE
Not able to do full clone from container

### ISSUE THREAD

**Issue by XDjackieXD** [Telmate/terraform-provider-proxmox#452] opened 2021-11-23 18:55 UTC
even when setting "full = true" in the lxc container config, I get `Error cloning LXC container: 500 parameter 'storage' not allowed for linked clones, error status`.
Doing a packet capture of the API servers internal port on the proxmox host reveals that the full option is not set in the clone http request to the API.

I'm using version v2.9.0 of the provider (as v2.9.1 doesn't work with containers at all)

**Comment by danfmihai** [comment] 2021-12-02 23:39
same issue here using v2.9.3
`Error: error cloning LXC container: 500 CT is locked (disk), error status:  (params: {"hostname":"ubuntu-qvqa-2","newid":411,"node":"proxmox","storage":"nvme","target":"proxmox","vmid":"400"})`

any idea what's wrong?

**Comment by TobiasS1402** [comment] 2022-01-04 08:34
Currenctly experiencing the same problem with v2.9.4 
```
Error: error cloning LXC container: 500 parameter 'storage' not allowed for linked clones, error status:  (params: {"hostname":"helios","newid":105,"node":"zeus","storage":"local-lvm","target":"zeus","vmid":"108"})
│ 
│   with proxmox_lxc.advanced_features[3],
│   on main.tf line 16, in resource "proxmox_lxc" "advanced_features":
│   16: resource "proxmox_lxc" "advanced_features" {
```

**Comment by yqlbu** [comment] 2022-02-27 11:04
Same problem happened to me!

**Comment by TobiasS1402** [comment] 2022-04-14 19:49
Just tried this on 2.9.7, sadly i still get the error. 
```
Error: error cloning LXC container: 500 CT is locked (disk), error status:  (params: {"hostname":"xxx","newid":111,"node":"xxx","storage":"local-lvm","target":"xxxx","vmid":"107"})
```

**Comment by yqlbu** [comment] 2022-04-15 02:26
Same for me. `2.9.7` does not resolve the issue yet.

**Comment by mleone87** [comment] 2022-04-15 10:46
A lot of confusion there!

`**500 parameter 'storage' not allowed for linked clones, error status**`
The error speaks itself, linked clone are only a same-storage feature, since its like how CoW filesystems works. **This is not a bug**, you cannot do linked clone in GUI either, I dont know how would you expect to do it elsewhere.
![ert](https://user-images.githubusercontent.com/807457/163562049-07f02177-0c7e-4f47-a458-f62f88653cf9.png)

`**500 CT is locked (disk)**`

There is some mess with the source container, too few infos to investigate

Closing this now, any other linked-clone/different storage issue will be closed.

Anyone else please open a complete issue with all the informations needed!

**Closed by mleone87** 2022-04-15 10:46 UTC

**Comment by XDjackieXD** [comment] 2022-04-15 15:17
Imo this issue still is an issue and has nothing to do with linked clones except for the error message.
I'm not trying to create a linked clone. Seeing this error message indicates to me that it tries to create a linked clone which is neither expected nor wanted when setting the option "full"...
The template is a fresh container created in proxmox with archlinux.

**Comment by yqlbu** [comment] 2022-04-15 15:37
Please re-consider this issue.

**Comment by mleone87** [comment] 2022-04-15 17:35
you are right that full clone is broken, actually the parameter is ignored!
Working on it but lxc clone functionality has a little work to do

**Comment by gihov** [comment] 2023-06-04 14:54
> you are right that full clone is broken, actually the parameter is ignored! Working on it but lxc clone functionality has a little work to do

I still have the issue, can it be re-open ?

**Comment by flygav1** [comment] 2024-05-06 00:19
Still having this issue
