### ISSUE TITLE
creating additional storage fails

### ISSUE THREAD

**Issue by csecsi** [Telmate/terraform-provider-proxmox#34] opened 2019-01-11 14:33 UTC
Terraform apply fails when I define additional disk(s). Error message varies depending the storage type:

ceph: * proxmox_vm_qemu.terra1: 500 unable to parse rbd volume name '103/vm-103-disk-1.raw'
lvm: * proxmox_vm_qemu.terra1: 500 lvm name '103/vm-103-disk-1.raw' contains illegal characters
local dir: * proxmox_vm_qemu.terra1: volume 'local:103/vm-103-disk-1.raw' does not exist

config snippet:

 disk {
    id           = 0
    type         = "virtio"
    storage      = "local"
    storage_type = "raw"
    size         = "20"
    backup       = "true"
  }

  disk {
    id           = 1
    type         = "virtio"
    storage      = "local"
    storage_type = "raw"
    size         = "1"
    backup       = "true"
  }

**Comment by alxkv** [comment] 2019-09-22 16:24
Hi! Not fixed yet? I have the same issue.

**Comment by cospeedster** [comment] 2019-12-03 09:20
@csecsi 
This should work now. Look at Telmate/terraform-provider-proxmox#94

**Comment by ata-sql** [comment] 2019-12-10 08:08
I stuck with same issue. Fix from #94 doesn't help, besides it looks like caused by something else.
I'm trying to add second disc to existing instance and it fails with:
`Error: 500 lvm name '169/vm-169-disk-2.raw' contains illegal characters`
When clicking in proxmox panel, new discs looks rather like "local-lvm:vm-169-disk-0" - without slash and dots.

**Comment by V-Paranoiaque** [comment] 2019-12-10 09:20
Could you share your tf file please? @ata-sql

**Comment by ata-sql** [comment] 2019-12-10 09:46
```
resource "proxmox_vm_qemu" "cloudinit-test" {

  lifecycle {
    ignore_changes = [ network ]
  }

  name = "centos-cloudinit-terraform"
  desc = "test"

  target_node = "pve-3"

  pool = "test"

  clone = "centos-cloudinit-template"

  os_type = "cloud-init"
  cores = 2
  sockets = 2
  memory = 4096
  scsihw = "virtio-scsi-pci"
  bootdisk = "scsi0"

  disk {
    id = 0
    size = 16
    type = "scsi"
    storage = "local-lvm"
  }

  disk {
    id = 1
    size = 16
    type = "scsi"
    storage = "local-lvm"
  }

  network {
    id = 0
    model = "virtio"
    bridge = "vmbr0"
    tag = 53
  }
}
```
Section with disk.id=1 is added after creating instance.

**Comment by kike29** [comment] 2020-07-06 16:11
> ```
> resource "proxmox_vm_qemu" "cloudinit-test" {
> 
>   lifecycle {
>     ignore_changes = [ network ]
>   }
> 
>   name = "centos-cloudinit-terraform"
>   desc = "test"
> 
>   target_node = "pve-3"
> 
>   pool = "test"
> 
>   clone = "centos-cloudinit-template"
> 
>   os_type = "cloud-init"
>   cores = 2
>   sockets = 2
>   memory = 4096
>   scsihw = "virtio-scsi-pci"
>   bootdisk = "scsi0"
> 
>   disk {
>     id = 0
>     size = 16
>     type = "scsi"
>     storage = "local-lvm"
>   }
> 
>   disk {
>     id = 1
>     size = 16
>     type = "scsi"
>     storage = "local-lvm"
>   }
> 
>   network {
>     id = 0
>     model = "virtio"
>     bridge = "vmbr0"
>     tag = 53
>   }
> }
> ```
> 
> Section with disk.id=1 is added after creating instance.

HI,


could you solve it.
Currently I have the same problem, when creating it with terraform it adds the .raw

**Comment by ayshfm1** [comment] 2020-09-10 21:58
I have the same problem

Error: 500 lvm name '129/vm-129-disk-0.raw' contains illegal characters

And it's not wrong

root@compute:~# lvcreate -l 20 -n 129/vm-129-disk-0.raw data
  Inconsistent volume group names given: "129" and "data"
  Run `lvcreate --help' for more information.

Can't prefix a logical volume with VM number it's not a volume group, you could prefix with the volume group, in this case data

root@compute:~# lvcreate -l 20 -n data/vm-129-disk-0.raw data
  Logical volume "vm-129-disk-0.raw" created.

Also was pointed out the logical volumes are not suffixed with .raw by proxmox

root@compute:~# vgdisplay -v|grep "LV Name"
  LV Name                vm-107-disk-0
  LV Name                vm-100-disk-0
  LV Name                vm-102-disk-0
  LV Name                vm-108-disk-0
  LV Name                vm-104-disk-0
  LV Name                vm-105-disk-0
  LV Name                vm-109-disk-0
  LV Name                vm-115-disk-0

**Comment by krusematt** [comment] 2020-10-16 00:19
I have the same issue.  I wanted to get a k3s cluster running.  I was following this guide: https://pawa.lt/posts/2019/07/automating-k3s-deployment-on-proxmox/

I noticed the same error within that guide, the vmID being a prefix, and the appended `.raw` :  `qm set 8000 --scsihw virtio-scsi-pci --scsi0 $STORAGE_POOL:8000/vm-8000-disk-0.raw`

Ultimately, I followed the template directions from: https://norocketscience.at/deploy-proxmox-virtual-machines-using-cloud-init/

Perhaps there is a difference between proxmox 5.x and 6.x? 

As for the proxmox provider/provisioner, I traced it back to the proxmox-go-api repo.

My issue was specific to:` storageType = "dir"`.  
https://github.com/Telmate/proxmox-api-go/blob/8138f8f4d517a1b4e0febf3439a83ee1c77837ed/proxmox/config_qemu.go#L906

Even though the comment two lines above states Directory is supported, it was omitted from the regex pattern.

I added it: https://github.com/Telmate/proxmox-api-go/commit/26a6a0676e8a0c6d7eba0822f42f43b3b339c904

As reference, I'm using Proxmox v6.1-7

Once I made the change, everything provisioned successfully,
```
module.k3s-cluster.proxmox_vm_qemu.generic-vm[1]: Creation complete after 1m25s [id=pve/qemu/105]
module.k3s-cluster.proxmox_vm_qemu.generic-vm[2]: Creation complete after 1m26s [id=pve/qemu/111]
module.k3s-cluster.proxmox_vm_qemu.generic-vm[3]: Creation complete after 1m26s [id=pve/qemu/106]
module.k3s-cluster.proxmox_vm_qemu.generic-vm[0]: Creation complete after 1m27s [id=pve/qemu/104]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
```

I'll make a merge request for this repo soon.  But if you see this before I have a chance, just update the `go.mod` file to `github.com/Telmate/proxmox-api-go 9161f9bf6a29` and `go mod tidy`.  The latest version will download and and `dir` storage type will be supported again.

Hope this helps someone.  I'm not 100% sure if it will solve your problem.  But I was not able to provision a machine successfully with `dir`, and it is the default setting.

**Comment by stets** [comment] 2020-10-21 02:23
@krusematt  you're a hero! This got rid of the error for me...
However, I had to reference the `proxmox-api-go` under `go.mod` in the terraform-provider-proxmox repo, rebuild the binaries and move them again into my `.terraform.d` plugins directory. But now I have another error on apply I need to go fix...

**Comment by Ramblurr** [comment] 2020-10-24 10:51
Also bitten by this. I'd rather not maintain  custom fork of proxmox-api-go, is there any chance this will be fixed here?

**Comment by imulab** [comment] 2021-03-10 20:58
For me, setting `storageType` to `lvm` did the trick.

**Closed** 2023-02-08 09:59 UTC
