### ISSUE TITLE
using "count" in vm creation causes terraform to run forever

### ISSUE THREAD

**Issue by jperez3** [Telmate/terraform-provider-proxmox#45] opened 2019-04-27 00:43 UTC
I've tried to use "count" in creating a new VM, but when I specify 2 or more instances, the terraform apply runs forever:

```
proxmox_vm_qemu.vm.1: Still creating... (7h44m24s elapsed)
proxmox_vm_qemu.vm.1: Still creating... (7h44m34s elapsed)
proxmox_vm_qemu.vm.0: Still creating... (7h44m34s elapsed)
```

When I run with a count of 1, it completes successfully. After the first has been created, I increment the count again to 2 and that works, but it fails/hangs when I go from 0 to 2.

**Comment by lunne** [comment] 2019-04-29 22:13
i have the asme problem just by specifing 3 resources and runing apply. It creates one and then it keeps "waiting for ...." 

If i exit and run it again it will create a second one..
If I repeat that it will create the third one.

destroy kills all 3 resources as expected.

**Comment by ggongaware** [comment] 2019-04-29 22:16
The Promox provider tries to do 4 (default) operations in parallel. Try setting to just 1 to see if its ok.

provider "proxmox" {
  pm_parallel = 1
}

**Comment by lunne** [comment] 2019-04-30 08:54
Thanks,
It looks like the problem is that nextVmId fails resolving the next valid ID.

Example:
- Existing vm with id (101, 102, 104, 105, 108)
- Create 3 resources (with or without count)
- pm_parallel = 1

It will get the first ID (103) correctly but the next one will fail:
[DEBUG] plugin.terraform-provider-proxmox: {"data":null,"errors":{"vmid":"VM 104 already exists"}})

I can see this in the API but I'm not sure why not always send the request without "?vmid=${vmid}" ?  
```
       if currentID >= 100 {
		url = fmt.Sprintf("/cluster/nextid?vmid=%d", currentID)
	} else {
		url = "/cluster/nextid"
	}
```

**Comment by ggongaware** [comment] 2019-05-01 17:20
We need to trace some more, but when the provider is making machines in pm_parallel > 1, the /cluster/nextid will return the same value, when asked multiple times before the actual node creation happens.

**Comment by jperez3** [comment] 2019-05-07 21:24
I just did a bit more googling on this and it looks like you guys ran into this before:

https://github.com/Telmate/terraform-provider-proxmox/issues/23

Also this is not specific to this provider, other people have had the same issue and suggest doing a wait/retry:
https://forum.proxmox.com/threads/qmrestore-doesnt-reserve-vmid.32260/#post-159554

Another option would be to allow the user to set the starting VMID, then you can increment that as well via `count`: 

```
resource "proxmox_vm_qemu" "vm" {
    count       = "${var.vm_count}"
    name        = "${var.vm_name}${count.index + 1}"
    vmid         =  "${count.index + var.vmid_begin}"
    ...
}

variable "vm_count" {
  default = "2"
}

variable "vm_name" {
  default = "test"
}
variable "vmid" {
  default = "301"
}
```

this would produce VMs test1 and test2 with VMIDs 301 and 302 respectively

**Comment by lunne** [comment] 2019-05-08 20:54
Hi,
I did a "dirty" fix that makes it possible to use vmid.
it also adds agent to the call so update is possible.

https://github.com/lunne/terraform-provider-proxmox
https://github.com/lunne/proxmox-api-go

**Comment by jperez3** [comment] 2019-05-09 20:58
@lunne I'm sorry, but I'm not seeing the difference between your fork and master. Can you please point out the difference? 
![Screen Shot 2019-05-09 at 1 56 37 PM](https://user-images.githubusercontent.com/21203946/57486198-6d711600-7262-11e9-8c97-d73c3df4ef64.png)

**Comment by lunne** [comment] 2019-05-10 06:01
Sorry, you need to select the branch "vmid" and on the api fork buggfixes-vmid

**Comment by jperez3** [comment] 2019-05-27 00:20
@lunne I added your changes, rebuilt the provider, gave it a new version number, but it still doesn't recognize `vmid` as a valid variable 😢 

 `invalid or unknown key: vmid`

**Comment by lunne** [comment] 2019-05-27 07:27
And you updated and rebuilt both the provider and the API with the branches?
https://github.com/lunne/terraform-provider-proxmox/tree/vmid
https://github.com/lunne/proxmox-api-go/tree/buggfixes-vmid

resource "proxmox_vm_qemu" "test" {
  vmid = 1010
}

Den mån 27 maj 2019 kl 02:20 skrev jperez3 <notifications@github.com>:

**Comment by OSN64** [comment] 2020-03-17 07:34
Unsure if this will fix your issues, but i set my `pm_parallel` variable to more than the number of vm's i was creating.
This seems to fix the infinite hang.

```
provider "proxmox" {
  pm_parallel = 20
}
```

**Comment by jperez3** [comment] 2020-03-18 01:30
> Unsure if this will fix your issues, but i set my `pm_parallel` variable to more than the number of vm's i was creating.
> This seems to fix the infinite hang.
> 
> ```
> provider "proxmox" {
>   pm_parallel = 20
> }
> ```

Thank you! I'll have to try this out!

**Comment by PatchesPrime** [comment] 2021-12-10 04:28
Hi, in searching for an answer to my problem I found this issue, which seems to be very close to what I'm having. Defining more than `pm_parallel` resources will cause the provider to hang indefinitely as it tries (but never actually tries, according to log) to provision them.

> Unsure if this will fix your issues, but i set my `pm_parallel` variable to more than the number of vm's i was creating. This seems to fix the infinite hang.
> 
> ```
> provider "proxmox" {
>   pm_parallel = 20
> }
> ```

My testing did show this to resolve the issue. I feel like this should not be necessary however.

**Closed** 2023-02-08 09:59 UTC
