### ISSUE TITLE
LXC - Error: a number is required

### ISSUE THREAD

**Issue by git-saj** [Telmate/terraform-provider-proxmox#535] opened 2022-04-14 22:04 UTC
Heya,

Experiencing an issue with LXCs on v2.9.7:

 Error: a number is required
│ 
│   with module.proxmox_lxc["****"].proxmox_lxc.proxmox_lxc,
│   on .terraform\modules\proxmox_lxc\modules\proxmox\proxmox_lxc\main.tf line 34, in resource "proxmox_lxc" "proxmox_lxc":
│   34:       mtu    = 1500
│ 

Same error with/without the MTU attribute specified

Thanks!

**Comment by briandipalma** [comment] 2022-04-15 06:37
Yeah also seeing this.

**Comment by briandipalma** [comment] 2022-04-15 06:39
```
│ Error: a number is required
│ 
│   with proxmox_lxc.work-docker,
│   on work-docker.tf line 22, in resource "proxmox_lxc" "work-docker":
│   22:   network {
```

**Comment by briandipalma** [comment] 2022-04-15 06:41
Duplicate of https://github.com/Telmate/terraform-provider-proxmox/issues/502 I don't get it are we meant to specify an MTU value?

**Comment by mleone87** [comment] 2022-04-15 09:07
you have inconsistent state file from older version where mtu was a string, either edit the state file or start from scratch with latest version and a clean state file

**Closed by mleone87** 2022-04-15 09:07 UTC
