### ISSUE TITLE
Linked clone is changed to full

### ISSUE THREAD

**Issue by goffinf** [Telmate/terraform-provider-proxmox#267] opened 2020-12-01 14:38 UTC
Proxmox version: **6.3-2**
Proxmox Terraform Provider version: **2.6.5**
Terraform version: **0.13.5**

**Description:**

When creating a VM where the **full_clone** attribute of the **proxmox_vm_qemu** resource is set to **false** ... the VM is created successfully from the declared template, however, when running a terraform plan again, terraform reports that the VM must be **replaced** because full_clone has been (re)set to **true** and Terraform wants to ensure that its state matches.

Its possible that converting a linked clone to a full clone is understandable behaviour by Proxmox in some circumstances (I saw some comments in various places that suggest as much), but of course it means that I wouldn't be able to update any VM details without causing the existing VM to be destroyed and recreated.

If I change the full_clone value in the main.tf to match state (true) then, as expected, terraform will not force that resource to be replaced.

Can anyone suggest whether this is expected or otherwise please ?

King Regards

Fraser.

**Inputs and Outputs:**

**main.tf** (module)

```
# Create the VM
resource "proxmox_vm_qemu" "proxmox_vm" {

  count = var.proxmox_node_count
  
  name        = "${var.hostname}-${count.index}"
  target_node = var.proxmox_target_node

  # basic instance config
  cores    = var.cores
  sockets  = var.sockets
  cpu      = var.cpu
  memory   = var.memory

  dynamic "disk" {
    for_each = var.additional_disks ? [1] : []
    content {
      iothread     = var.disk_info["iothread"]
      slot         = var.disk_info["slot"]
      size         = var.disk_info["size"]
      ssd         = var.disk_info["ssd"]
      storage      = var.disk_info["storage"]
      type         = var.disk_info["type"]
    }
  }

  serial {
    id   = var.serial["id"]
    type = var.serial["type"]
  }

  # Clone from the pre-prepared template (e.g. ubuntu-20-04-cloudinit-template)
  agent      = var.agent
  clone      = var.proxmox_template
  full_clone = var.full_clone
  os_type  = var.proxmox_os_type
 
  # Cloud init options
  cicustom = "user=local:snippets/${var.cloud_config_template}-${count.index}.yml"
  ipconfig0 = var.ipconfig0

  ciuser     = var.proxmox_ssh_user
  cipassword = var.proxmox_ssh_pwd

  sshkeys = <<EOF
${var.ssh_key}
EOF

  # boot disk paramters
  boot     = var.boot_device
  bootdisk = var.boot_disk
  scsihw   = var.boot_scsi_hw

  # network config
  network {
    model  = var.network["model"]
    bridge = var.network["bridge"]
  }

  # Ignore changes to the network
  # MAC address is generated on every apply, causing
  # TF to think that this needs to be rebuilt on every apply
  
  lifecycle {
    ignore_changes = [
      network,
    ]
  }
}
```

**Output from initial apply:**

```
terraform apply --auto-approve
module.vault_vm.module.proxmox_cloud_init_snippets.data.template_file.cloud_init_snippet[0]: Refreshing state...
module.vault_vm.module.proxmox_cloud_init_snippets.local_file.cloud_init_snippet[0]: Creating...
module.vault_vm.module.proxmox_cloud_init_snippets.local_file.cloud_init_snippet[0]: Creation complete after 0s [id=4cf5a3928c827f1467706fcb902501df24d0b0ad]
module.vault_vm.module.proxmox_cloud_init_snippets.null_resource.cloud_init_snippet[0]: Creating...
module.vault_vm.module.proxmox_cloud_init_snippets.null_resource.cloud_init_snippet[0]: Provisioning with 'file'...
module.vault_vm.proxmox_vm_qemu.proxmox_vm[0]: Creating...
module.vault_vm.module.proxmox_cloud_init_snippets.null_resource.cloud_init_snippet[0]: Creation complete after 5s [id=9199471119067041721]
module.vault_vm.proxmox_vm_qemu.proxmox_vm[0]: Still creating... [10s elapsed]
module.vault_vm.proxmox_vm_qemu.proxmox_vm[0]: Still creating... [20s elapsed]
module.vault_vm.proxmox_vm_qemu.proxmox_vm[0]: Still creating... [30s elapsed]
module.vault_vm.proxmox_vm_qemu.proxmox_vm[0]: Still creating... [40s elapsed]
module.vault_vm.proxmox_vm_qemu.proxmox_vm[0]: Still creating... [50s elapsed]
module.vault_vm.proxmox_vm_qemu.proxmox_vm[0]: Creation complete after 51s [id=pve/qemu/113]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

**Output from subsequent plan:** (no changes in the main.tf, variable values or tfvars)

```
terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.vault_vm.module.proxmox_cloud_init_snippets.data.template_file.cloud_init_snippet[0]: Refreshing state... [id=d280607f404198f01799cfe9f86328d4361a84b4e671a493018774908affe591]
module.vault_vm.module.proxmox_cloud_init_snippets.local_file.cloud_init_snippet[0]: Refreshing state... [id=4cf5a3928c827f1467706fcb902501df24d0b0ad]
module.vault_vm.module.proxmox_cloud_init_snippets.null_resource.cloud_init_snippet[0]: Refreshing state... [id=9199471119067041721]
module.vault_vm.proxmox_vm_qemu.proxmox_vm[0]: Refreshing state... [id=pve/qemu/113]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.vault_vm.proxmox_vm_qemu.proxmox_vm[0] must be replaced
-/+ resource "proxmox_vm_qemu" "proxmox_vm" {
        agent                  = 1
        balloon                = 0
        bios                   = "seabios"
        boot                   = "c"
        bootdisk               = "scsi0"
        cicustom               = "user=local:snippets/cloud-init-ubuntu-20.04-base-0.yml"
        cipassword             = (sensitive value)
        ciuser                 = "root"
        clone                  = "ubuntu-20-04-1-vault-template"
        clone_wait             = 15
        cores                  = 1
        cpu                    = "host"
        define_connection_info = true
      - disk_gb                = 0 -> null
        force_create           = false
      ~ full_clone             = true -> false # forces replacement
        ...

```

**Comment by mandrav** [comment] 2020-12-04 18:50
I 'm seeing the exact same behavior, v2.6.5 from terraform registry.
Adding full_clone to lifecycle's ignore_changes is _not_ helping either.

**Comment by AcidCrash1337** [comment] 2020-12-24 14:52
I believe that the issue is this [line of code](https://github.com/Telmate/terraform-provider-proxmox/blob/61a2083f63facaeb38c74fbb75d47c484637ece6/proxmox/resource_vm_qemu.go#L184) but I haven't been able to figure out how to compile this project, so I can't test that change.

**Comment by dapeng235** [comment] 2021-02-03 03:11
遇到同样问题，期待尽快解决
We are looking forward to solving the same problem as soon as possible

**Comment by tagur87** [comment] 2021-05-05 12:25
I think the issue is actually related more to this line. 
https://github.com/Telmate/terraform-provider-proxmox/blob/61a2083f63facaeb38c74fbb75d47c484637ece6/proxmox/resource_vm_qemu.go#L1103

When reading the current state, it is not possible to read from the api whether the vm is a full clone or a linked clone. The code is just forcing the value to what was set in terraform config, however I don't think that is working as expected. 

I will dig into the code a bit to see if I can find a fix for this.

**Closed** 2021-05-07 14:39 UTC

**Comment by goffinf** [comment] 2021-05-07 14:51
@tagur87 (Joel), thanks for the fix. At what point will this be included in a release ?

**Comment by tagur87** [comment] 2021-05-07 16:08
Not sure @goffinf... I'm not a maintainer. @ggongaware  would have to tag a new release for this to be updated in the registry.
