### ISSUE TITLE
[3.0.1-rc1][BUG] QEMU Guest Agent is always enabled

### ISSUE THREAD

**Issue by dawidtomczyk** [Telmate/terraform-provider-proxmox#934] opened 2024-02-10 23:02 UTC
Hi.
According to the documentation by default agent should be set to 0 (disabled).

QEMU Guest Agent is always enabled. Changing to 0 does not work.

Proxmox version: 8.1.4

**Comment by babblerz** [comment] 2024-02-19 21:20
I can confirm this.
If you have it enabled in your template then it cannot be disabled (agent = 0 is ignored).
If you have it disabled in your template then it can stay disabled by omitting the agent parameter or setting agent = 0 (simply because it is ignored) or can be enabled with agent = 1.

This could be an issue with the api where the value 0 is treated as an invalid value.
```
if config.Agent != 0 {
		params["agent"] = config.Agent
}
```
There are two different places where the same code appears:
https://github.com/Telmate/proxmox-api-go/blob/b043e37def62aad374c848259dd1832ee4a85fd4/proxmox/config_qemu.go#L305C2-L307C3

https://github.com/Telmate/proxmox-api-go/blob/b043e37def62aad374c848259dd1832ee4a85fd4/proxmox/config_qemu.go#L1053C2-L1055C3

**Comment by hestiahacker** [comment] 2024-02-20 00:11
I can confirm this, thanks for the additional info @babblerz :slightly_smiling_face: 

To be clear, when the qemu agent enabled in the template:

* Omitting the `agent` line from the terraform does not disable the agent in Proxmox and
* Explicitly setting `agent=0` also does not disable the agent in Proxmox

**Comment by dawidtomczyk** [comment] 2024-03-13 17:02
Sorry for not responding. Will you be able to fix this issue? It doesn't allow me to destroy Talos Linux VM's.

Thanks!

**Comment by hestiahacker** [comment] 2024-03-25 15:01
@dawidtomczyk An issue was [created in the library](https://github.com/Telmate/proxmox-api-go/issues/323) that needs to be changed to fix this bug. So a fix is in the queue.

As a workaround until this is fixed, you should be able to disable the agent in the template VM that you are cloning and it will be disabled in the VMs based on your template.

**Closed** 2024-04-18 17:05 UTC
Labels: bug
